nodeLinker: node-modules
enableTelemetry: false
httpTimeout: 300000
networkConcurrency: 1

# Force HTTPS for git repositories
packageExtensions:
  "*@*":
    dependencies:
      git: "https://github.com/"