const ClaudeCodeAssistant = require('./claude-api');
const fs = require('fs');
const { execSync } = require('child_process');

async function autoFixWorkflow(command = 'full') {
    const claude = new ClaudeCodeAssistant();
    
    try {
        console.log('🚀 Starting Meta Aggregator 2.0 Auto-Fix Workflow...');
        console.log('🔑 API Key configured:', process.env.ANTHROPIC_API_KEY ? 'YES' : 'NO');
        
        // Check command type
        switch (command) {
            case 'analyze':
                await runAnalysisOnly(claude);
                break;
            case 'ui-only':
                await runUIFixesOnly(claude);
                break;
            case 'fix':
            case 'full':
            default:
                await runFullWorkflow(claude);
                break;
        }
        
    } catch (error) {
        console.error('❌ Error in auto-fix workflow:', error.message);
        if (error.message.includes('credit') || error.message.includes('rate limit')) {
            console.error('� Check your Anthropic API credits/rate limits in the dashboard');
        }
    }
}

async function runAnalysisOnly(claude) {
    console.log('\n📋 Running Project Analysis...');
    const analysis = await claude.analyzeProject();
    console.log('✅ Analysis complete - saved to .claude-output/analysis.md');
    
    await generateAnalysisReport(analysis);
}

async function runUIFixesOnly(claude) {
    console.log('\n🔧 Running UI Fixes Generation...');
    const fixes = await claude.fixUIIssues();
    console.log('✅ UI fixes generated - saved to .claude-output/ui-fixes.md');
    
    await generateUIFixesReport(fixes);
}

async function runFullWorkflow(claude) {
    console.log('\n📋 Phase 1: Project Analysis...');
    const analysis = await claude.analyzeProject();
    console.log('✅ Analysis complete');
    
    console.log('\n🔧 Phase 2: UI Fixes Generation...');
    const fixes = await claude.fixUIIssues();
    console.log('✅ UI fixes generated');
    
    console.log('\n📝 Phase 3: Implementation Ready');
    console.log('📁 Check these files for detailed fixes:');
    console.log('   - claude-session.log (full session log)');
    console.log('   - .claude-output/analysis.md (project analysis)');
    console.log('   - .claude-output/ui-fixes.md (specific fixes)');
    
    console.log('\n🎯 Next Steps:');
    console.log('1. Review the generated fixes in .claude-output/');
    console.log('2. Apply fixes to your source files');
    console.log('3. Test the changes');
    console.log('4. Run: npm run build (to verify fixes)');
    
    // Generate summary
    await generateSummary(analysis, fixes);
}

async function generateAnalysisReport(analysis) {
    const report = `# Meta Aggregator 2.0 - Project Analysis Report

Generated: ${new Date().toISOString()}

## 📊 Analysis Results

${analysis}

## 🎯 Next Steps
1. Review the analysis above
2. Run UI fixes: \`node .devcontainer/auto-fix.js ui-only\`
3. Apply the suggested changes
4. Test the application

---
*Generated by Claude Code Assistant*
`;

    fs.writeFileSync('.claude-output/analysis.md', report);
    console.log('📋 Analysis report saved: .claude-output/analysis.md');
}

async function generateUIFixesReport(fixes) {
    const report = `# Meta Aggregator 2.0 - UI Fixes Report

Generated: ${new Date().toISOString()}

## 🔧 UI Fixes

${fixes}

## 🎯 Implementation Steps
1. Apply the code changes above in order
2. Test each component after changes
3. Run \`npm run build\` to verify compilation
4. Test in browser for runtime errors

---
*Generated by Claude Code Assistant*
`;

    fs.writeFileSync('.claude-output/ui-fixes.md', report);
    console.log('📋 UI fixes report saved: .claude-output/ui-fixes.md');
}

async function generateSummary(analysis, fixes) {
    const summary = `# Meta Aggregator 2.0 - Claude Analysis Summary

Generated: ${new Date().toISOString()}

## 🔍 Analysis Overview
${analysis.substring(0, 500)}...

## 🔧 Critical Fixes Needed
${fixes.substring(0, 500)}...

## 📋 Implementation Checklist
- [ ] Fix ethers.js v6 compatibility issues
- [ ] Update TypeScript configuration
- [ ] Fix React component prop types
- [ ] Resolve Docker build issues
- [ ] Update package.json dependencies
- [ ] Test all components
- [ ] Verify Docker build
- [ ] Run integration tests

## 📁 Files Generated
- analysis.md - Complete project analysis
- ui-fixes.md - Specific code fixes
- claude-session.log - Full session log

## 🎯 Priority Order
1. package.json & tsconfig.json fixes
2. Ethers.js v6 updates in components
3. React prop type fixes
4. Docker build improvements
5. Integration testing
`;

    fs.writeFileSync('/workspace/.claude-output/summary.md', summary);
    console.log('📋 Summary generated: .claude-output/summary.md');
}

async function runSpecificFix(fileName, issue) {
    const claude = new ClaudeCodeAssistant();
    console.log(`🔧 Generating specific fix for ${fileName}...`);
    
    try {
        const fix = await claude.generateSpecificFix(fileName, issue);
        const outputFile = `/workspace/.claude-output/fix-${fileName.replace('/', '-')}.md`;
        fs.writeFileSync(outputFile, fix);
        console.log(`✅ Fix generated: ${outputFile}`);
    } catch (error) {
        console.error(`❌ Error generating fix for ${fileName}:`, error.message);
    }
}

// Command line interface
const args = process.argv.slice(2);
if (args[0] === 'fix' && args[1]) {
    runSpecificFix(args[1], args[2] || 'General fixes needed');
} else if (args[0] === 'analyze') {
    (async () => {
        const claude = new ClaudeCodeAssistant();
        await claude.analyzeProject();
    })();
} else if (args[0] === 'ui-fixes') {
    (async () => {
        const claude = new ClaudeCodeAssistant();
        await claude.fixUIIssues();
    })();
} else {
    // Run full workflow if called directly
    if (require.main === module) {
        autoFixWorkflow();
    }
}

module.exports = { autoFixWorkflow, runSpecificFix, runAnalysisOnly, runUIFixesOnly, runFullWorkflow };
